<?php

/**
 * @file
 * Drupal.nl Meetup importer.
 */

use Drupal\drupalnl_meetup\Util;

/**
 * Implements hook_cron().
 */
function drupalnl_meetup_cron() {
  // If run longer than an hour ago.
  if (\Drupal::state()->get('drupalnl_meetup_last_run') < \Drupal::time()->getRequestTime() - 3600) {
    // @todo This could use a config form.
    $urls = [
      'https://api.meetup.com/drupalnl/events',
      'https://api.meetup.com/drupalnetherlands/events',
      'https://api.meetup.com/drupal-amsterdam/events',
    ];

    foreach ($urls as $url) {
      $source = Util::runImport($url);
      $message = Util::meetupSourceComposeMessage($source);

      \Drupal::logger('drupalnl_meetup')->notice($message['message'], $message['variables']);
    }

    // Set when we last ran.
    \Drupal::state()->set('drupalnl_meetup_last_run', \Drupal::time()->getRequestTime());
  }
}
